import "./globals.css";
import Script from "next/script";
import Header from "../components/Header";
import Footer from "../components/Footer";

// ✅ 함수 아님! 준비된 객체를 import
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // ✅ 폰트는 html(className/variable) 또는 body에 적용하면 됩니다.
    <html lang="ko" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <head>
        {/* Lordicon 애니메이션 스크립트 */}
        <Script src="https://cdn.lordicon.com/lordicon.js" strategy="beforeInteractive" />
      </head>
      <body className="antialiased">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
